[project]
name = "KGraphPy"
version = "0.2.2"
description = "Plugin for rdflib for handling parsing and serialization of cim graphs."
requires-python = ">=3.12"
dependencies = [
    "build>=1.5.0",
    "linkml>=1.9.6",
    "rdflib[graphdb]>=7.5.0",
]

[tool.setuptools]
packages = ["cim_plugin"]

[tool.setuptools.package-data]
cim_plugin = ["*.yaml"]

[tool.pytest.ini_options]
pythonpath = [
    "."
]
markers = [
    "stress: long-running stress tests"
]
addopts = "-m 'not stress' -rP"
